### ISSUE TITLE
Improving documentation: Add descriptions to reference pages

### ISSUE THREAD

**Issue by ekoner** [ThreeSixtyGiving/standard#174]
We build the html references pages e.g. [Actual Dates](http://www.threesixtygiving.org/standard/reference/#toc-actual-dates) from csv files e.g. [actualDates.csv](https://github.com/ThreeSixtyGiving/standard/blob/master/documentation/src/tabledefs/actualDates.csv).

However we don't include the object's description. e.g. for actualDate:description it would be "When did this grant activity actually take place. Dates should be in YYYY-MM-DD format. A date range can include a start date and duration in months, or a start and end date."

As part of improving the documentation shown on the website to make it clearer, more consistent and easier to use, I'd like this description to appear in the web page under the title. This feature is available on the [Grants Sheet](http://www.threesixtygiving.org/standard/reference/#toc-grants-sheet).

Having this feature in means I can focus on flagging places in the underlying schema where the <object>:description isn't clear.

**Comment by timgdavies** [comment]
I've [had a go in this branch](https://github.com/ThreeSixtyGiving/standard/tree/174-documentation-updates) at an approach to fix this which updates the build_docs.py script so that:

* Embedding csv tables continues to work as before
* If the string between {{ and }} does not contain .csv, it is treated as a JSON path for a value within the JSON schema, and embeds the requested element

This means I can update the source file for reference.md to include all the descriptions from the schema, [which can be seen in action here](https://github.com/ThreeSixtyGiving/standard/blob/174-documentation-updates/documentation/reference.md)

Will put a pull request for @bjwebb and colleagues to review.

**Comment by ekoner** [comment]
Now live - issue closed
