### ISSUE TITLE
Provide a link back to main 360 site 

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#206]
@morchickit please can you consider how we link back to the main 360 site from http://standard.threesixtygiving.org/en/latest/

Example: OCDS link back through a logo in the sidebar: http://standard.open-contracting.org/latest/en/ - 

Something similar could be done here (perhaps differently worded?) - @Bjwebb can also advise

**Comment by morchickit** [comment]
I agree that a logo will be the best option.

On 24 Jul 2017 5:36 p.m., "Steven Flower" <notifications@github.com> wrote:

Assigned #206 <https://github.com/ThreeSixtyGiving/standard/issues/206> to
@morchickit <https://github.com/morchickit>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ThreeSixtyGiving/standard/issues/206#event-1176471114>,
or mute the thread

**Comment by caprenter** [comment]
We agreed an approach in a google doc of next steps. This was not a logo in the end, but it could be.

When considering a logo I thought
1) Which logo?
2) The main logo on the 360Giving website, might not look good when made small enough to fit the documentation sidebar
3) The logo would also need words or at the least a tool tip and alt text

..therefore, just go with text for now

**Comment by morchickit** [comment]
Guys, you asked if the logo is fine, I said OK. We have many sizes, so we can fit it. If text is easier for you, let's do text....

**Comment by caprenter** [comment]
ok
