### ISSUE TITLE
Data Quality Tool - LAE flag

### ISSUE THREAD

**Issue by Julianlstar** [ThreeSixtyGiving/standard#210]
Data Quality Tool throws up an Additional Check flag against organisations that have their identifiers derived from the Local Authority Register https://local-authority-eng.register.gov.uk

**Comment by timgdavies** [comment]
Flagging @robredpath to check if this needs a codelist updated for the data quality tool, or whether this has to wait for integration with org-id.guide to happen.

**Comment by robredpath** [comment]
The org prefix additional check currently uses the IATI 2.02 OrganisationRegistrationAgency codelist. Switching over to org-id.guide would definitely be a useful thing to do in the near future. I've added https://github.com/OpenDataServices/cove/issues/796 on the CoVE repo, as this issue relates to the DQT rather than the standard.
