### ISSUE TITLE
Field suggestion: Award Type

### ISSUE THREAD

**Issue by practicalparticipation** [ThreeSixtyGiving/standard#26]
Forward Foundation have suggested including an 'Award Type' classification against grants, to indicate:

> "the type of money the grant is composed of e.g. Restricted, Semi-restricted, Core costs, etc (list needs revision and funder consensus)."

This could be introduced as a form of classification - although we would need to identify how easy it would be for funders to provide this information.

**Comment by prbass** [comment]
Semi-restricted is a new one for me. Think the only meaningful distinction would be "Restricted" or "Unrestricted" but not sure how many trusts would hold/release this information as data rather than in their grant making policy. 

An unrestricted grant can be used by the recipient for any purpose (and if they are a charity for any activity in pursuit of their charitable objectives) while a restricted grant can only be used for a specific purpose (often requiring unspent funds to be returned). 

These originate from trust law, which is fairly arcane, and often misunderstood - even by the accountants and local authority funders who should know better e.g. you see contractual income being recorded as restricted funds in accounts 

Charities can create "designated funds" which show that a fund is being held for a specific purpose - e.g. for a new building, but these are unrestricted funds and can be undesignated

**Comment by suninthesky** [comment]
"Restricted", "Unrestricted", works for me. Suraj @ Forward Foundation

**Comment by stevieflow** [comment]
I observed (#53) via the Wellcome Trust data that ``Grant type`` was used to describe various internal programmes / categories , so consideration would be needed in terms of making this field clear in terms of intended usage

**Comment by practicalparticipation** [comment]
Would a simple boolean flag here for 'Restricted income' make sense for the meaning we want for 'Award Type'? 

And then other things can belong in classifications.

**Comment by suninthesky** [comment]
@practicalparticipation That can work.

Re: 'Award Type':
For [Beehive](http://beehivegiving.org/) we are interested in both grants and social investments as a single funder can often provide both. I'm new to the world of social finance - do you think a social investment would fit into 'Restricted income', or something else? Do you think the standard will be able to support social investments as well as grants?

**Comment by practicalparticipation** [comment]
I believe we can capture social investments, though I suspect inferring investment from a boolean flag for restricted might not make sense. 

We could go back to the idea of a codelist here, and have:

* Unrestricted grant
* Restricted grant
* Investment

Thoughts?

**Comment by suninthesky** [comment]
Could two boolean fields work? Just puzzling over if the [restrictedness](http://www.fit4funding.org.uk/support-pages/when-you-receive-funding/restricted-funding/) of a grant/investment is conceptually different from it's repay-ability (is that a word)?

|            | Restricted? | Repayable? |
|------------|-------------|------------|
| Grant      | T           | F          |
| Grant      | F           | F          |
| Investment | T           | T          |
| Investment | F           | T          |

**Comment by prbass** [comment]
I'd advise against introducing any social investment fields into the
360giving standard at this stage. We've just not done the research
required, and I think we'd just risk confusing the core of users who are
just making grants.

The booleans above don't work -  restricted grants are usually repayable.

To do social investment justice we'd have to consider and understand a
whole range of instruments from bonds, social impact bonds, loans, equity
deals, for some people performance related contracts are also a social
investment. And we'd also have to think about how to capture interest
rates, terms, etc.

There are currently very few social investments being made, partly because
the complexity of them makes them really expensive to make and receive. To
put it into context EngagedX have spent about 4 years developing a data
standard to record social investments, and when I met them last summer they
had collected data about fewer than 50 investment deals.

**Comment by suninthesky** [comment]
Thanks @prbass, makes sense. I'm meeting with a number of social investors to feed into our R&D and will feedback anything relevant.

@practicalparticipation The codelist works for us.

**Comment by morchickit** [comment]
Similar discussion about type was in program type in #188

**Comment by morchickit** [comment]
We do have a field name funding type - http://standard.threesixtygiving.org/en/latest/reference/#funding-type 
Are we referring to the same thing?

**Comment by stevieflow** [comment]
Action here is to decide whether this is about 

- a new field ( ``awardType``), which id different from ``fundingType``
- a codelist (which should be a forum discussion on the need for codelists) 
- both /none

**Comment by morchickit** [comment]
Created topic in the forum here. https://forum.threesixtygiving.org/t/award-type-field/21 
Closing this. Please comment on the forum.
