### ISSUE TITLE
Firefox is blocking the schema browsers

### ISSUE THREAD

**Issue by duncandewhurst** [ThreeSixtyGiving/standard#303]
I don't recall changing any security settings, but as of yesterday https://standard.threesixtygiving.org/en/latest/reference/#giving-json-schemas looks like this:

![image](https://user-images.githubusercontent.com/19265814/127428734-56d2eefd-5fc4-4fef-b1c7-23efc06eb135.png)

**Comment by robredpath** [comment]
Interesting. If I click that link in my Firefox, it works! 

I think the error is https://support.mozilla.org/en-US/kb/xframe-neterror-page , but I can't see either of the mentioned headers in the HTTP response (Content-Security-Policy or X-Frame-Options). Of course, that might be because it's working for me, now. 

I notice https://github.com/readthedocs/readthedocs.org/commit/2740e075ab0a27995c399b2c74017b165ebe466b - a very recent commit to ReadTheDocs source code that deals with this. I'm not quite sure on what the timeline would be, but that's awfully suspicious, so I suspect that this was a case of RTD's config and code not quite matching up for a little while, before getting noticed and fixed. 

If this is still happening, please do comment again - or if it's now fixed, I'm reasonably happy with ^^ being the explanation and happy to close.

**Comment by duncandewhurst** [comment]
Thanks, Rob. Seems to be working again now, so I guess that was it.
