### ISSUE TITLE
Publications with grants that have one Classification

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/standard#66]
If/when a grant has one classification code per grant , the documentation seems to suggest that this should be a separate table:

http://www.threesixtygiving.org/standard/reference/#toc3

> To provide classifications of grants, more than one location, or additional documents related to the grant, you will need to publish information in sub-tables. 

However - in this use case, could a single classification sit in the Grants Sheet?

**Comment by timgdavies** [comment]
Yes. See http://www.threesixtygiving.org/standard/reference/#toc15

Adding fields for

| Classification:Vocabulary | Classification:Code | Classification:Title | 
|---|---|---|

should be possible, although there might be some tweaks to the flatten tool/cove required before the conversion of that to JSON works properly (can you test and liase with Ben on the changes required and when they are scheduled)

**Comment by stevieflow** [comment]
Great, thanks @timdavies - makes sense

**Comment by stevieflow** [comment]
@Bjwebb how best to proceed?

**Comment by stevieflow** [comment]
@bjwebb @kindly @caprenter I think this is still the case?  A single Classification cannot be published in the grant sheet?

cc @ekoner

**Comment by timgdavies** [comment]
This is definitely one of the things that I hope gets sorted with flatten tool developments coming up...

**Comment by Bjwebb** [comment]
Yes, I think this is this issue again https://github.com/OpenDataServices/flatten-tool/issues/50 ? Definitely planning to get this one cracked next week.

**Comment by Bjwebb** [comment]
The rollup titles bug is now fixed in flattentool, see the commits against https://github.com/OpenDataServices/flatten-tool/issues/50 . This is now available for testing at http://flatten-tool-updates.dev.cove.opendataservices.coop/360/

Note that the appropriate fields are actually currently:

| Classifications:Vocabulary | Classifications:Code | Classifications:Title | 
|---|---|---|

ie. the plural Classification**s** rather than Classification, as the former is the `title` in the schema.

I think is the correct behaviour, so will close this this issue for now.
