### ISSUE TITLE
Include check for Award Date format

### ISSUE THREAD

**Issue by ekoner** [ThreeSixtyGiving/standard#98]
The Award Date must be in the format YYYY-MM-DD according to http://www.threesixtygiving.org/standard/reference/

Can this be implemented in the json standard and added to CoVE?

**Comment by caprenter** [comment]
In the schema, Award Date is stipulated as a 'date-time':
https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json#L472

For validators, this causes a problem - i.e. they will check for a datetime (basically YYYY-MM-DDTHH:MM:SS(+Timezone)) - as we are only asking publishers for a date.

So anyone writing a validator needs to be aware of this. (We cannot alter the schema to require only a date, unless we rolled back to a draft3 version of the JSON Schema, which is not something to be done lightly). In CoVE's case we can modify the format checking, so we can indeed make our schema checks check for just a date. See: https://github.com/OpenDataServices/cove/issues/194

So essentially the problem here is that the rule enforced by the schema definitions is out of line with the advice we give to publishers. For most this is a minor technicality, but for anyone wanting to use the schema to validate data this is an important piece of information.

**Comment by stevieflow** [comment]
@ekoner @caprenter @kindly @bjwebb with https://github.com/OpenDataServices/cove/issues/194 closed, is this an issue still?

**Comment by caprenter** [comment]
Sorry, I'd written a comment when I set the wont fix label, but must not have submitted it.

The issue is one we can't fix with the json4 schema, and this issue is therefore really one for the consuming applications to deal with. CoVE has made it's choices, so this issue can be left for others to see, but there is no action

**Comment by caprenter** [comment]
See also: https://github.com/ThreeSixtyGiving/standard/pull/128

**Comment by ekoner** [comment]
Closing issue
